import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const errors=[],checks=[],performance=[];const base=process.env.PREVIEW_URL||'http://127.0.0.1:5173';
function watch(page){page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});}
const page=await browser.newPage({viewport:{width:1440,height:960}});watch(page);
async function fixture(p){await p.evaluate(()=>{const {match:m,follow}=window.dropStudio;m.bots=false;m.phase='active';m.countdown=-1;for(const t of m.tiles){t.gone=!t.startsPresent;t.state=t.gone?'gone':'stable';t.activatedAt=null;t.expires=Infinity;}for(const [i,a] of m.players.entries()){a.alive=true;a.removed=false;a.position.set(0,m.data.levels[0]+.15,i===0?2.35:-4.7);a.velocity.set(0,0,0);a.grounded=true;a.support=m.tileAt(0,a.position.x,a.position.z);a.input={x:0,z:0};}const a=m.players[0],l=m.launchers[0];if(a.launcher!==null){m.launchers[a.launcher].state='waiting';a.launcher=null;}l.state='resting';l.owner=null;l.tile=a.support;l.position.copy(a.position);l.vy=0;follow.yaw=0;follow.pitch=.18;});await p.waitForTimeout(150);}
try{
 await page.goto(base);await page.waitForFunction(()=>window.dropStudio?.match);await page.evaluate(()=>localStorage.setItem('pizzeria-drop-controls-seen','1'));assert.equal(await page.evaluate(()=>window.dropStudio.match.tiles.every(t=>!t.gone)),true);
 await page.click('#play');await page.waitForFunction(()=>window.dropStudio.match.phase==='active');await page.waitForFunction(()=>window.dropStudio.match.players[0].grounded);
 const first=await page.evaluate(()=>{const p=window.dropStudio.match.players[0];return{state:p.support.state,at:p.support.activatedAt,deadline:p.support.expires};});assert.equal(first.state,'activated');assert(Math.abs(first.deadline-first.at-3)<.001);checks.push('real countdown → initial drop → first contact activates tile');
 const before=await page.evaluate(()=>window.dropStudio.match.players[0].position.toArray());await page.keyboard.down('KeyD');await page.waitForTimeout(250);await page.keyboard.up('KeyD');assert((await page.evaluate(()=>window.dropStudio.match.players[0].position.x))>before[0]+.1);
 await page.keyboard.press('Space');await page.waitForTimeout(250);assert((await page.evaluate(()=>window.dropStudio.match.players[0].position.y))>before[1]+1);await page.keyboard.press('KeyE');await page.waitForTimeout(60);assert((await page.evaluate(()=>window.dropStudio.match.players[0].velocity.y))<0);checks.push('desktop WASD / Space / E');
 const high=await page.evaluate(()=>window.dropStudio.camera.position.y);await page.evaluate(()=>{const d=window.dropStudio,p=d.match.players[0];p.position.set(0,4.35,0);p.velocity.set(0,0,0);d.match.bots=false;});await page.waitForTimeout(900);const low=await page.evaluate(()=>window.dropStudio.camera.position.y);assert(low<high-5);assert(low<11.1);checks.push('camera descends with player and stays below overhead floor');
 await fixture(page);assert.equal(await page.evaluate(()=>window.dropStudio.match.players[0].ammo),2);assert(await page.evaluate(()=>window.dropStudio.actors[0].weapon.visible));
 await page.keyboard.down('KeyF');await page.waitForTimeout(450);assert((await page.evaluate(()=>window.dropStudio.match.players[0].lock.seconds))>0);await page.evaluate(()=>window.dropStudio.match.players[1].position.x=6);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.dropStudio.match.players[0].lock.seconds),0);await page.keyboard.up('KeyF');
 await fixture(page);await page.keyboard.down('KeyF');await page.waitForFunction(()=>window.dropStudio.match.players[0].lock.locked,{timeout:3000});await page.screenshot({path:'assets/reports/correction-lock.png'});await page.keyboard.up('KeyF');assert.equal(await page.evaluate(()=>window.dropStudio.match.players[0].ammo),1);await page.waitForFunction(()=>window.dropStudio.match.events.some(e=>e.type==='rocket-impact'));const hit=await page.evaluate(()=>window.dropStudio.match.events.find(e=>e.type==='rocket-impact'));assert.equal(hit.tiles.length,4);checks.push('contact auto-equip; visible handheld gun; reticle leave resets; real F hold/release locks and removes exactly four tiles');
 await page.click('#exit-match');await page.click('#roster');await page.evaluate(()=>window.rosterActors.forEach(a=>a.weapon.visible=true));
 for(const clip of ['idle','run','jump','fall','landing','recovery','hit','dance']){await page.selectOption('#animation',clip);await page.waitForTimeout(120);const distances=await page.evaluate(()=>window.rosterActors.flatMap(a=>['Right','Left'].map(side=>a.model.getObjectByName(side+'Hand').getWorldPosition(a.model.position.clone()).distanceTo(a.weapon.getObjectByName(side+'Grip').getWorldPosition(a.model.position.clone())))));assert(distances.every(d=>d<.10),`${clip} grip distances ${distances}`);}checks.push('both mascots maintain both grip positions in all eight animation clips');await page.selectOption('#animation','idle');await page.screenshot({path:'assets/reports/correction-grip.png'});
 await page.click('#return');await page.click('[data-world="cityscape"]');await page.click('[data-difficulty="hard"]');while((await page.evaluate(()=>window.dropStudio.state.crowd))!==15)await page.click('#crowd');await page.screenshot({path:'assets/reports/correction-cityscape.png'});await page.click('#play');await page.waitForTimeout(3900);await page.screenshot({path:'assets/reports/correction-city-play.png'});
 for(const world of ['cityscape','volcano']){if(world==='volcano'){await page.click('#exit-match');await page.click('[data-world="volcano"]');await page.click('#play');await page.waitForTimeout(3900);}const metric=await page.evaluate(async()=>{const samples=[];let t=performance.now();for(let i=0;i<120;i++){await new Promise(requestAnimationFrame);const now=performance.now();samples.push(now-t);t=now;}samples.sort((a,b)=>a-b);return{...window.dropStudio.state,medianFrameMs:samples[60],p95FrameMs:samples[114],alive:window.dropStudio.match.players.filter(p=>p.alive).length};});performance.push(metric);}checks.push('15-character active simulations in both worlds');
 const mobile=await browser.newPage({viewport:{width:844,height:390},deviceScaleFactor:1,isMobile:true,hasTouch:true});watch(mobile);await mobile.goto(base);await mobile.waitForFunction(()=>window.dropStudio?.match);await mobile.evaluate(()=>localStorage.setItem('pizzeria-drop-controls-seen','1'));await mobile.click('[data-world="cityscape"]');await mobile.click('#play');await mobile.waitForTimeout(3700);await fixture(mobile);const client=await mobile.context().newCDPSession(mobile);
 const rect=async selector=>{const b=await mobile.locator(selector).boundingBox();return{x:b.x+b.width/2,y:b.y+b.height/2};};const joy=await rect('#joystick'),fire=await rect('#touch-fire');const touch=(id,x,y)=>({id,x,y,radiusX:3,radiusY:3,force:1});
 const start=await mobile.evaluate(()=>({x:window.dropStudio.match.players[0].position.x,yaw:window.dropStudio.follow.yaw}));await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,joy.x+28,joy.y),touch(2,480,160),touch(3,fire.x,fire.y)]});await mobile.waitForTimeout(220);assert(await mobile.evaluate(()=>window.dropStudio.match.players[0].lock.holding));await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,joy.x+28,joy.y),touch(2,540,175),touch(3,fire.x,fire.y)]});await mobile.waitForTimeout(180);assert((await mobile.evaluate(()=>window.dropStudio.match.players[0].position.x))>start.x+.05);assert(Math.abs((await mobile.evaluate(()=>window.dropStudio.follow.yaw))-start.yaw)>.1);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await mobile.evaluate(()=>window.dropStudio.match.players[0].ammo),2);checks.push('landscape simultaneous real touches: joystick + camera drag + held fire');
 await fixture(mobile);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(3,fire.x,fire.y)]});await mobile.waitForFunction(()=>window.dropStudio.match.players[0].lock.locked,{timeout:3000});await mobile.screenshot({path:'assets/reports/correction-mobile-landscape.png'});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await mobile.evaluate(()=>window.dropStudio.match.players[0].ammo),1);checks.push('landscape touch two-second lock and release fire');
 await fixture(mobile);await mobile.tap('#touch-jump');await mobile.waitForTimeout(180);assert((await mobile.evaluate(()=>window.dropStudio.match.players[0].velocity.y))>0);await mobile.tap('#touch-dive');await mobile.waitForTimeout(60);assert((await mobile.evaluate(()=>window.dropStudio.match.players[0].velocity.y))<0);checks.push('touch Jump and Dive');
 await mobile.evaluate(()=>{const p=window.dropStudio.match.players[0];p.position.y=-.7;});await mobile.waitForTimeout(900);assert.equal(await mobile.evaluate(()=>window.dropStudio.actors[0].model.visible),false);checks.push('eliminated body renderer disappears');assert.deepEqual(errors,[]);
 fs.writeFileSync('assets/reports/correction-browser-validation.json',JSON.stringify({environment:'Local Chrome headless, desktop 1440x960 and actual Chromium touch events at 844x390; not a Staige or physical-phone certification.',checks,performance,errors},null,2));console.log(JSON.stringify({checks,performance,errors},null,2));
}finally{await browser.close();}
